spring:
  application:
    name: qa-admin
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  mail:
    host: localhost
    port: 2525
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  devtools:
    livereload:
      enabled: true
server:
  port: 8080
logging:
  level:
    web: debug