---
name: codecov
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: gradle b
      - name: install admin-client deps
        working-directory: qa-admin/src/main/client
        run: npm ci
      - name: admin-client coverage
        working-directory: qa-admin/src/main/client
        run: npm coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./qa-admin/build/reports/jacoco/test/jacocoTestReport.xml, ./qa-rest/build/reports/jacoco/test/jacocoTestReport.xml, ./qa-admin/src/main/client/coverage/clover.xml
          fail_ci_if_error: true
